/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import FormCokolada.FormNovaCokolada;
import FormCokolada.FormPretragaCokolade;
import FormKupac.FormNoviKupac;
import FormKupac.FormPretragaKupca;
import controller.ClientController;
import domain.Administrator;
import domain.Cokolada;
import domain.Kupac;
import domain.Racun;
import domain.StavkaRacuna;
import domain.VrstaCokolade;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.TableModelStavkeRacuna;
import session.Session;

/**
 *
 * @author Danica
 */
public class MainForm extends javax.swing.JFrame implements Runnable {

    Administrator a;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        this.a = Session.getInstance().getTrenutnoUlogovani();
        lblUlogovani.setText("Ulogovani administrator: " + a);
        setTitle("Klijentska forma");
        Thread th = new Thread(this);
        th.start();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUlogovani = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        lblDatumVreme = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbKupac = new javax.swing.JComboBox();
        txtUkupanIznos = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnDodaj = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        cmbVrstaCokolade = new javax.swing.JComboBox();
        cmbCokolada = new javax.swing.JComboBox();
        txtKolicina = new javax.swing.JFormattedTextField();
        txtCenaStavke = new javax.swing.JFormattedTextField();
        btnSacuvaj = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        miNovaCokolada = new javax.swing.JMenuItem();
        miPretragaCokolade = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        miNoviKupac = new javax.swing.JMenuItem();
        miPretragaKupca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUlogovani.setText("Ulogovani");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos racuna"));

        jLabel1.setText("Kupac:");

        jLabel2.setText("Ukupan iznos:");

        cmbKupac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtUkupanIznos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos stavki racuna"));

        jLabel3.setText("Vrsta cokolade:");

        jLabel4.setText("Cokolada:");

        jLabel5.setText("Kolicina:");

        jLabel6.setText("Cena stavke:");

        btnDodaj.setText("Dodaj stavku");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi stavku");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavke);

        cmbVrstaCokolade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbVrstaCokolade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbVrstaCokoladeItemStateChanged(evt);
            }
        });

        cmbCokolada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCokolada.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCokoladaItemStateChanged(evt);
            }
        });

        txtKolicina.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtKolicina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKolicinaKeyReleased(evt);
            }
        });

        txtCenaStavke.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbVrstaCokolade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCokolada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtKolicina)
                            .addComponent(txtCenaStavke))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbVrstaCokolade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCokolada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCenaStavke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnObrisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnSacuvaj.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnSacuvaj.setText("Sacuvaj racun");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbKupac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUkupanIznos)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbKupac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu7.setText("Cokolada");

        miNovaCokolada.setText("Nova cokolada");
        miNovaCokolada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNovaCokoladaActionPerformed(evt);
            }
        });
        jMenu7.add(miNovaCokolada);

        miPretragaCokolade.setText("Pretraga cokolade");
        miPretragaCokolade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaCokoladeActionPerformed(evt);
            }
        });
        jMenu7.add(miPretragaCokolade);

        jMenuBar1.add(jMenu7);

        jMenu6.setText("Kupac");

        miNoviKupac.setText("Novi kupac");
        miNoviKupac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNoviKupacActionPerformed(evt);
            }
        });
        jMenu6.add(miNoviKupac);

        miPretragaKupca.setText("Pretraga kupca");
        miPretragaKupca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaKupcaActionPerformed(evt);
            }
        });
        jMenu6.add(miPretragaKupca);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUlogovani)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 556, Short.MAX_VALUE)
                        .addComponent(lblDatumVreme, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDatumVreme, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUlogovani))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miNoviKupacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNoviKupacActionPerformed
        if (Session.getInstance().getTrenutnoUlogovani().getAdministratorID() == 1) {
            new FormNoviKupac(this, true).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Nemate pristup ovoj operaciji!");
        }
    }//GEN-LAST:event_miNoviKupacActionPerformed

    private void miPretragaKupcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaKupcaActionPerformed
        if (Session.getInstance().getTrenutnoUlogovani().getAdministratorID() == 1) {
            new FormPretragaKupca(this, true).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Nemate pristup ovoj operaciji!");
        }
    }//GEN-LAST:event_miPretragaKupcaActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

        int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da "
                + "se odjavite?", "Konfirmacija", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.NO_OPTION) {
            return;
        }

        if (result == JOptionPane.YES_OPTION) {
            new Login().setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_btnLogoutActionPerformed

    private void miNovaCokoladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNovaCokoladaActionPerformed
        new FormNovaCokolada(this, true).setVisible(true);
    }//GEN-LAST:event_miNovaCokoladaActionPerformed

    private void miPretragaCokoladeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaCokoladeActionPerformed
        new FormPretragaCokolade(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaCokoladeActionPerformed

    private void cmbVrstaCokoladeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbVrstaCokoladeItemStateChanged

        if (cmbVrstaCokolade.getSelectedItem() != null) {

            VrstaCokolade vc = (VrstaCokolade) cmbVrstaCokolade.getSelectedItem();
            popuniCokolade(vc);

        }

    }//GEN-LAST:event_cmbVrstaCokoladeItemStateChanged

    private void txtKolicinaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKolicinaKeyReleased

        try {
            if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')
                    || evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {

                if (txtKolicina.getText().isEmpty()) {
                    txtCenaStavke.setText("0.00");
                    return;
                }

                Cokolada c = (Cokolada) cmbCokolada.getSelectedItem();
                double kolicina = Double.parseDouble(txtKolicina.getText());

                txtCenaStavke.setText(String.valueOf(c.getCenaPoKG() * kolicina));

            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Morate uneti broj u kolicinu!");
        }


    }//GEN-LAST:event_txtKolicinaKeyReleased

    private void cmbCokoladaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCokoladaItemStateChanged

        if (cmbCokolada.getSelectedItem() != null) {

            if (txtKolicina.getText().isEmpty()) {
                txtCenaStavke.setText("0.00");
                return;
            }

            Cokolada c = (Cokolada) cmbCokolada.getSelectedItem();
            double kolicina = Double.parseDouble(txtKolicina.getText());

            txtCenaStavke.setText(String.valueOf(c.getCenaPoKG() * kolicina));

        }

    }//GEN-LAST:event_cmbCokoladaItemStateChanged

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed

        if (txtKolicina.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate uneti kolicinu stavke!");
            return;
        }

        Cokolada c = (Cokolada) cmbCokolada.getSelectedItem();
        double kolicina = Double.parseDouble(txtKolicina.getText());
        double cenaStavke = Double.parseDouble(txtCenaStavke.getText());

        StavkaRacuna sr = new StavkaRacuna(null, -1, kolicina, cenaStavke, c);

        TableModelStavkeRacuna tm = (TableModelStavkeRacuna) tblStavke.getModel();
        tm.dodajStavku(sr);

        double ukupanIznos = Double.parseDouble(txtUkupanIznos.getText());

        ukupanIznos += sr.getCenaStavke();

        txtUkupanIznos.setText(String.valueOf(ukupanIznos));


    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed

        int row = tblStavke.getSelectedRow();

        if (row >= 0) {
            TableModelStavkeRacuna tm = (TableModelStavkeRacuna) tblStavke.getModel();
            
            StavkaRacuna sr = tm.getStavka(row);

            double ukupanIznos = Double.parseDouble(txtUkupanIznos.getText());

            ukupanIznos -= sr.getCenaStavke();

            txtUkupanIznos.setText(String.valueOf(ukupanIznos));

            tm.obrisiStavku(row);
        }

    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        
        Kupac k = (Kupac) cmbKupac.getSelectedItem();
        double ukupanIznos = Double.parseDouble(txtUkupanIznos.getText());
        
        TableModelStavkeRacuna tm = (TableModelStavkeRacuna) tblStavke.getModel();
        
        Racun r = new Racun(null, new Date(), ukupanIznos, k, a, tm.getLista());
        
        try {
            ClientController.getInstance().addRacun(r);
            JOptionPane.showMessageDialog(this, "Sistem je kreirao račun!");
            srediFormu();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            //Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbCokolada;
    private javax.swing.JComboBox cmbKupac;
    private javax.swing.JComboBox cmbVrstaCokolade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDatumVreme;
    private javax.swing.JLabel lblUlogovani;
    private javax.swing.JMenuItem miNovaCokolada;
    private javax.swing.JMenuItem miNoviKupac;
    private javax.swing.JMenuItem miPretragaCokolade;
    private javax.swing.JMenuItem miPretragaKupca;
    private javax.swing.JTable tblStavke;
    private javax.swing.JFormattedTextField txtCenaStavke;
    private javax.swing.JFormattedTextField txtKolicina;
    private javax.swing.JFormattedTextField txtUkupanIznos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (true) {
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy HH:mm:ss");
            lblDatumVreme.setText("Datum i vreme: " + sdf.format(new Date()));
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void srediFormu() {
        popuniKupce();
        txtUkupanIznos.setText("0.00");
        txtUkupanIznos.setEnabled(false);
        txtCenaStavke.setText("0.00");
        txtCenaStavke.setEnabled(false);
        popuniVrsteCokolade();
        tblStavke.setModel(new TableModelStavkeRacuna());
    }

    public void popuniKupce() {
        try {
            ArrayList<Kupac> kupci = ClientController.getInstance().getAllKupac();

            cmbKupac.removeAllItems();

            for (Kupac kupac : kupci) {
                cmbKupac.addItem(kupac);
            }

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void popuniVrsteCokolade() {
        try {
            ArrayList<VrstaCokolade> vrsteCokolada = ClientController.getInstance().getAllVrstaCokolade();

            cmbVrstaCokolade.removeAllItems();

            for (VrstaCokolade vrstaCokolade : vrsteCokolada) {
                cmbVrstaCokolade.addItem(vrstaCokolade);
            }

            popuniCokolade(vrsteCokolada.get(0));

        } catch (Exception ex) {
            Logger.getLogger(FormNovaCokolada.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void popuniCokolade(VrstaCokolade vc) {
        try {
            ArrayList<Cokolada> cokolade = ClientController.getInstance().getAllCokolada(vc);

            cmbCokolada.removeAllItems();

            for (Cokolada cokolada : cokolade) {
                cmbCokolada.addItem(cokolada);
            }

        } catch (Exception ex) {
            Logger.getLogger(FormNovaCokolada.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
